# Generated by Django 5.2.3 on 2025-06-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=512)),
                ('price', models.IntegerField()),
                ('discount_price', models.IntegerField()),
                ('rating', models.FloatField()),
                ('feedbacks', models.IntegerField()),
            ],
        ),
    ]
